version: '3.8'

services:
  school-be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-be
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./docker/entrypoint.sh:/usr/local/bin/entrypoint.sh
    networks:
      - school
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=school
      - DB_USERNAME=school
      - DB_PASSWORD=school
    ports:
      - "8000:80"


  caddy:
    image: caddy:2
    container_name: school_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./docker/caddy/data:/data
      - ./docker/caddy/config:/config
      # - ./:/var/www/html
    networks:
      - school
    depends_on:
      - school-be

  db:
    image: mysql:8
    container_name: school_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: school
      MYSQL_USER: school
      MYSQL_PASSWORD: school
      MYSQL_ROOT_PASSWORD: 1ncrease
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - school

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: school_phpmyadmin
    restart: unless-stopped      
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1ncrease
      UPLOAD_LIMIT: 300M
    networks:
      - school
    depends_on:
      - db

  portainer:
    image: portainer/portainer-ce
    container_name: school_portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - school

volumes:
  db_data:
  portainer_data:

networks:
  school:
    name: school
